### PR TITLE
specify custom separator

### PR DESCRIPTION
**Pull request by webbpinner**
Add optional custom separator between timestamp and data string

### CODE REVIEW

**Comment by webbpinner** [comment]
Easy add-on

**Comment by davidpablocohn** [comment]
Thanks! Precisely what I was going to suggest. But would you be willing to change the keyword from 'separator' to 'sep' to be consistent with convention used by the python split() method and the [logger/transforms/prefix_transform.py](logger/transforms/prefix_transform.py)?

**Comment by webbpinner** [comment]
ok... change completed

**Comment by davidpablocohn** [comment]
Thanks for this! Merged.

**Pull request merged**
